# Form implementation generated from reading ui file 'ApiConfig.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ApiConfig(object):
    def setupUi(self, ApiConfig):
        ApiConfig.setObjectName("ApiConfig")
        ApiConfig.resize(413, 300)
        self.label = QtWidgets.QLabel(parent=ApiConfig)
        self.label.setGeometry(QtCore.QRect(30, 10, 111, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=ApiConfig)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 121, 41))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=ApiConfig)
        self.pushButton.setGeometry(QtCore.QRect(230, 250, 161, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=ApiConfig)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 250, 91, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=ApiConfig)
        self.lineEdit.setGeometry(QtCore.QRect(140, 10, 251, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=ApiConfig)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 50, 251, 32))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textBrowser = QtWidgets.QTextBrowser(parent=ApiConfig)
        self.textBrowser.setGeometry(QtCore.QRect(20, 90, 371, 151))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(ApiConfig)
        self.lineEdit_2.returnPressed.connect(self.pushButton_2.click) # type: ignore
        self.lineEdit.returnPressed.connect(self.pushButton_2.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ApiConfig)

    def retranslateUi(self, ApiConfig):
        _translate = QtCore.QCoreApplication.translate
        ApiConfig.setWindowTitle(_translate("ApiConfig", "Form"))
        self.label.setText(_translate("ApiConfig", "ChatGPT API key"))
        self.label_2.setText(_translate("ApiConfig", "RapidAPI key"))
        self.pushButton.setText(_translate("ApiConfig", "Register RapidAI API key"))
        self.pushButton_2.setText(_translate("ApiConfig", "Submit"))
        self.textBrowser.setHtml(_translate("ApiConfig", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Connection details:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[<span style=\" color:#00557f;\">*</span>] Awaiting...</p></body></html>"))
