# Form implementation generated from reading ui file 'BypassMenu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BypassMenu(object):
    def setupUi(self, BypassMenu):
        BypassMenu.setObjectName("BypassMenu")
        BypassMenu.resize(400, 300)
        self.start_button = QtWidgets.QPushButton(parent=BypassMenu)
        self.start_button.setGeometry(QtCore.QRect(50, 260, 111, 31))
        self.start_button.setDefault(False)
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(parent=BypassMenu)
        self.stop_button.setGeometry(QtCore.QRect(230, 260, 111, 31))
        self.stop_button.setDefault(False)
        self.stop_button.setObjectName("stop_button")
        self.label = QtWidgets.QLabel(parent=BypassMenu)
        self.label.setGeometry(QtCore.QRect(30, 0, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(parent=BypassMenu)
        self.textBrowser.setGeometry(QtCore.QRect(10, 40, 381, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(parent=BypassMenu)
        self.label_2.setGeometry(QtCore.QRect(250, 0, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(BypassMenu)
        QtCore.QMetaObject.connectSlotsByName(BypassMenu)
        BypassMenu.setTabOrder(self.start_button, self.stop_button)
        BypassMenu.setTabOrder(self.stop_button, self.textBrowser)

    def retranslateUi(self, BypassMenu):
        _translate = QtCore.QCoreApplication.translate
        BypassMenu.setWindowTitle(_translate("BypassMenu", "SEBuster is ready"))
        self.start_button.setText(_translate("BypassMenu", "Start"))
        self.stop_button.setText(_translate("BypassMenu", "Stop"))
        self.label.setText(_translate("BypassMenu", "Secure Exam Buster is:"))
        self.textBrowser.setHtml(_translate("BypassMenu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Instructions</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To consult ChatGPT, write a command starting with &quot;/c&quot; followed by a prompt. After writing the command, copy it to the clipboard using CTRL + C.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Examples</span>:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">• /c Who is Mary Shelley?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">• /c Describe the perfect sandwich</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you have WolframAlpha set up, you can consult it similarly by using &quot;/w&quot; instead.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Examples</span>:<br />• /w Cumulative household income for Connecticut vs Wisconsin</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">• /w Simplify (a + b)(a - b)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">After your command has been copied, wait for 10 seconds, then paste the clipboard contents with CTRL + V. The answer should be pasted.</p></body></html>"))
        self.label_2.setText(_translate("BypassMenu", "inactive"))
