# Form implementation generated from reading ui file 'WolframAlpha.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Wfram(object):
    def setupUi(self, Wfram):
        Wfram.setObjectName("Wfram")
        Wfram.resize(451, 292)
        self.connect_button = QtWidgets.QPushButton(parent=Wfram)
        self.connect_button.setGeometry(QtCore.QRect(180, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.connect_button.setFont(font)
        self.connect_button.setObjectName("connect_button")
        self.help_button = QtWidgets.QPushButton(parent=Wfram)
        self.help_button.setGeometry(QtCore.QRect(310, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.help_button.setFont(font)
        self.help_button.setObjectName("help_button")
        self.label = QtWidgets.QLabel(parent=Wfram)
        self.label.setGeometry(QtCore.QRect(20, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.w_apikey = QtWidgets.QLineEdit(parent=Wfram)
        self.w_apikey.setGeometry(QtCore.QRect(150, 10, 281, 21))
        self.w_apikey.setObjectName("w_apikey")
        self.w_connection = QtWidgets.QTextBrowser(parent=Wfram)
        self.w_connection.setGeometry(QtCore.QRect(20, 40, 411, 191))
        self.w_connection.setObjectName("w_connection")

        self.retranslateUi(Wfram)
        QtCore.QMetaObject.connectSlotsByName(Wfram)

    def retranslateUi(self, Wfram):
        _translate = QtCore.QCoreApplication.translate
        Wfram.setWindowTitle(_translate("Wfram", "WolframAlpha Setup"))
        self.connect_button.setText(_translate("Wfram", "Connect"))
        self.help_button.setText(_translate("Wfram", "Help"))
        self.label.setText(_translate("Wfram", "Wolfram API key"))
        self.w_connection.setHtml(_translate("Wfram", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Connection:</span></p></body></html>"))
